# run: conda env create --file environment.yml
name: ltl_mrta
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.10.12
  - pip
  # - anaconda::pygraphviz
  - pip:
    - -r requirements.txt